### ISSUE TITLE
display game over when no moves are possible

### ISSUE THREAD

**Issue by thepmsquare** [thepmsquare/2048#1]

**Comment by nghianv-1868** [comment]
You want the game over when the mouse is not moving for a long time or until the game time is over

**Comment by yencolon** [comment]
Hi, I think I can help you with this issue :)

**Comment by thepmsquare** [comment]
give it a try.

**Comment by yencolon** [comment]
Done, but this not participating in Hacktoberfest haha

**Comment by thepmsquare** [comment]
@yencolon i'll add the label on the pr.

**Comment by thepmsquare** [comment]
thank you for your contribution @yencolon .
