### ISSUE TITLE
need to add background color to tiles

### ISSUE THREAD

**Issue by thepmsquare** [thepmsquare/2048#2]
tiles with same values need to have same background color. preferably colors that belong in material-ui color palette.

**Comment by ArturBa** [comment]
I'm interested, please sign me in

**Comment by KushalBhanot** [comment]
Hey! I can try this out.

**Comment by thepmsquare** [comment]
sure both of you can try it out. @ArturBa  @KushalBhanot

**Comment by thepmsquare** [comment]
thanks for your contribution. #3 was accepted and this issue is closed.
